### ISSUE TITLE
Weird textures bug.

### ISSUE THREAD

**Issue by CloserPopcorn20** [MC-Legacy-Projects/Legacy-Remade#4]
It happens with all texture packs for some reason. If these blocks are far from you, their sides become weirdly dark, but the blocks, which are near you look fine.
![2024-10-16_21 33 29](https://github.com/user-attachments/assets/9e6fc235-e2c0-46cb-8758-6b0364af2740)

**Comment by Permdog99** [comment]
This is actually a problem with Legacy Mipmaps conflicting with Sodium. If it's bugging you at all, then I would suggest turning off Legacy Mipmaps for now.

**Comment by Permdog99** [comment]
Closed. Won't be fixed as not related to Remade.
